# Generated by Django 5.1 on 2024-09-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodId', models.IntegerField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=15)),
                ('foodPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restarent',
            fields=[
                ('restarentId', models.IntegerField(primary_key=True, serialize=False)),
                ('restarentName', models.CharField(max_length=15)),
                ('restarentLocation', models.CharField(max_length=15)),
            ],
        ),
    ]
